apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmeter-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: jmeter-server
    spec:
      containers:
        - name: jmeter-server-container
          image: registry.eu-gb.bluemix.net/evrim/jmeter-server
          imagePullPolicy: Always
          ports:
            - containerPort: 31099
              containerPort: 32000
          args:
            - '-Dserver.rmi.localport=32000 -Dserver.rmi.localhostname=169.51.15.131 -Djava.rmi.server.hostname=169.51.15.131'
          env:
            - name: "SERVER_PORT"
              value: "31099"
              volumeMounts:
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-server-service
  labels:
    run: jmeter-server
spec:
  type: NodePort
  selector:
    run: jmeter-server
  ports:
   - name: "rmi"
     port: 31099
     protocol: TCP
     targetPort: 31099
     nodePort: 31099
   - name: "service"
     port: 32000
     protocol: TCP
     targetPort: 32000
     nodePort: 32000
